[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"

# Redirect for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://generativelanguage.googleapis.com https://openrouter.ai https://*.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://generativelanguage.googleapis.com https://openrouter.ai https://*.supabase.co https://api.openai.com https://graph.microsoft.com https://api.notion.com wss://*.supabase.co; media-src 'self' blob: https://*.supabase.co;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# OAuth callback redirects
[[redirects]]
  from = "/auth/google/callback"
  to = "/oauth/callback"
  status = 200

[[redirects]]
  from = "/auth/microsoft/callback"
  to = "/oauth/callback"
  status = 200

[[redirects]]
  from = "/auth/notion/callback"
  to = "/oauth/callback"
  status = 200